name: verl2
channels:
  - nvidia
  - https://conda.anaconda.org/nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.9.1
  - cuda-compiler=12.9.1
  - cuda-crt-dev_linux-64=12.9.86
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart-dev=12.9.79
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-cupti-dev=12.9.79
  - cuda-cuxxfilt=12.9.82
  - cuda-driver-dev=12.9.79
  - cuda-driver-dev_linux-64=12.9.79
  - cuda-gdb=12.9.79
  - cuda-libraries=12.9.1
  - cuda-libraries-dev=12.9.1
  - cuda-nsight=12.9.79
  - cuda-nvcc=12.9.86
  - cuda-nvcc-dev_linux-64=12.9.86
  - cuda-nvcc-impl=12.9.86
  - cuda-nvcc-tools=12.9.86
  - cuda-nvcc_linux-64=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvml-dev=12.9.79
  - cuda-nvprof=12.9.79
  - cuda-nvprune=12.9.82
  - cuda-nvrtc=12.9.86
  - cuda-nvrtc-dev=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-dev_linux-64=12.9.86
  - cuda-nvvm-impl=12.9.86
  - cuda-nvvm-tools=12.9.86
  - cuda-nvvp=12.9.79
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-sanitizer-api=12.9.79
  - cuda-toolkit=12.9.1
  - cuda-tools=12.9.1
  - cuda-version=12.9
  - cuda-visual-tools=12.9.1
  - cudnn=9.10.2.21
  - dbus=1.16.2
  - expat=2.7.1
  - fontconfig=2.15.0
  - freetype=2.13.3
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.14.1.1
  - gmp=6.3.0
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - icu=73.1
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libcublas=12.9.1.4
  - libcublas-dev=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.4.1.4
  - libcufft-dev=11.4.1.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusolver-dev=11.7.5.82
  - libcusparse=12.5.10.65
  - libcusparse-dev=12.5.10.65
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libglib=2.84.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnpp=12.4.1.87
  - libnpp-dev=12.4.1.87
  - libnvfatbin=12.9.82
  - libnvfatbin-dev=12.9.82
  - libnvjitlink=12.9.86
  - libnvjitlink-dev=12.9.86
  - libnvjpeg=12.4.0.76
  - libnvjpeg-dev=12.4.0.76
  - libpng=1.6.50
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - ncurses=6.5
  - nsight-compute=2025.2.1.3
  - nspr=4.37
  - nss=3.89.1
  - ocl-icd=2.3.2
  - openssl=3.0.18
  - pcre2=10.46
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.12.0
  - readline=8.3
  - sqlite=3.50.2
  - sysroot_linux-64=2.17
  - tk=8.6.15
  - wheel=0.45.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - astor==0.8.1
      - asttokens==3.0.0
      - attrs==25.4.0
      - av==16.0.1
      - blake3==1.0.8
      - blobfile==3.0.0
      - build==1.3.0
      - cachetools==6.2.1
      - cbor2==5.7.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.1
      - codetiming==1.4.0
      - colorful==0.5.7
      - compressed-tensors==0.11.0
      - contourpy==1.3.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.1
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==4.3.0
      - decorator==5.2.1
      - decord==0.6.0
      - depyf==0.19.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - executing==2.2.1
      - fastapi==0.120.1
      - fastapi-cli==0.0.14
      - fastapi-cloud-cli==0.3.1
      - fastrlock==0.8.3
      - filelock==3.20.0
      - fire==0.7.1
      - flash-attn==2.8.3
      - flashinfer-python==0.3.1
      - fonttools==4.61.1
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.0
      - google-auth==2.41.1
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - interegular==0.3.3
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - liger-kernel==0.6.3
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - math-verify==0.8.0
      - mathruler==0.1.0
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - modelscope==1.31.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.15.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - openai==1.99.1
      - openai-harmony==0.0.4
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-fixer==0.2.5
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-prometheus==0.59b0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - optree==0.17.0
      - orjson==3.11.4
      - outlines==0.1.11
      - outlines-core==0.2.11
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post6
      - pebble==5.1.3
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycparser==2.23
      - pycryptodomex==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pylatexenc==2.10
      - pynvml==13.0.1
      - pyparsing==3.3.1
      - pyproject-hooks==1.2.0
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - ray==2.50.1
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rpds-py==0.28.0
      - rsa==4.9.1
      - ruff==0.14.2
      - safetensors==0.6.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - setuptools==79.0.1
      - sgl-kernel==0.3.9.post2
      - sglang==0.5.2
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.4.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - starlette==0.49.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.10.0
      - termcolor==3.2.0
      - tiktoken==0.12.0
      - timeout-decorator==0.5.0
      - timm==1.0.16
      - tokenizers==0.22.1
      - torch==2.8.0
      - torch-memory-saver==0.0.8
      - torchao==0.9.0
      - torchaudio==2.8.0
      - torchdata==0.11.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.1
      - triton==3.4.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - virtualenv==20.35.3
      - vllm==0.11.0
      - wandb==0.22.2
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - word2number==1.1
      - wrapt==2.0.0
      - xformers==0.0.32.post1
      - xgrammar==0.1.25
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
